Controllers/Tutorial2Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DataTableEditable.Controllers
{
    public class Tutorial2Controller : Controller
    {
        //
        // GET: /Tutorial2/

        public ActionResult Index()
        {
            ViewBag.MenuTitle = "Please Click to See Changes";
            ViewBag.SectionTitle = "Please look at the changes below";
            return View();
        }

        [HttpGet]
        public ActionResult _PartialPick(int id)
        {
            if (id.Equals(1))
            {
                return PartialView("_Partial1");
            }
            else if (id.Equals(2))
            {
                return PartialView("_Partial2");
            }
            else if (id.Equals(3))
            {
                return PartialView("_Partial3");
            }
            else
            {
                return PartialView("_Partial4");
            }
        }
    }
}

Views/Tutorial2/Index.cshtml
@{
    ViewBag.Title = "Negative Zero Tutorial : Part 3";
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/part3.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/modernizr-1.7.min.js")" type="text/javascript"></script>
</head>
<body>
    <div class="page">
        <header>
            <div id="title">
                <h1>Tutorial : Part 3 - Negative Zero</h1>
            </div>
            <div id="logindisplay">
                Dummy Login
            </div>
            <nav>
                <ul id="menu">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Company", "Index", "Company")</li>
                    <li>@Html.ActionLink("Partial", "Index", "Tutorial2")</li>
                </ul>
            </nav>
        </header>
        <section id="main">
        <div id="wrapper">
            <div id="wrapper" class="left-box">
                <p class="section-title">
                    @ViewBag.MenuTitle
                </p>
                <ul id="left-box" class="menu-left-box">
                    <li><a class="LinkPart" href="#" onclick="getPartial(1);">Partial 1</a></li>
                    <li><a class="LinkPart" href="#" onclick="getPartial(2);">Partial 2</a></li>
                    <li><a class="LinkPart" href="#" onclick="getPartial(3);">Partial 3</a></li>
                    <li><a class="LinkPart" href="#" onclick="getPartial(4);">Partial 4</a></li>
                    <li>@Html.ActionLink("Done", "Index")</li>
                </ul>
            </div>
            <div class="right-box">
                <p class="section-title">
                    Part 3: @ViewBag.SectionTitle
                </p>
                <div id="right-box" class="data" style="visibility:visible;">
                   @* Section to display partial forms *@ 
                   @Html.Partial("_DefaultPartial")
                </div>
            </div>
            <script type="text/javascript">
                function getPartial(y) {
                    $.get('/Tutorial2/_PartialPick/'+ y, function (data) {
                            $('div#right-box.data').html(data);
                        });
                }
            </script>
            <div class="clear">
            </div>
        </div>
   </section>
</body>
<footer>Negative Zero &reg; Tutorials<br />Copyleft &copy; 2011</footer>
</html>

Views/Tutorial2/_DefaultPartial.cshtml
<h3>This Partial is being viewed by default</h3>

<p>I am located in div with id=right-box and class=data</p>

Views/Tutorial2/_Partial1.cshtml
<h3>This Partial is being viewed by default</h3>

<h1>PARTIAL 1 LOADED</h1>

Views/Tutorial2/_Partial2.cshtml
<h3>This Partial is being viewed by default</h3>

<h1>PARTIAL 2 LOADED</h1>

Views/Tutorial2/_Partial3.cshtml
<h3>This Partial is being viewed by default</h3>

<h1>PARTIAL 3 LOADED</h1>

Views/Tutorial2/_Partial4.cshtml
<h3>This Partial is being viewed by default</h3>

<h1>PARTIAL 4 LOADED</h1>